import { boardStory, dealRoom, payload, readinessLane, redFlagMap, summary, verification } from "./verticalBriefService.js";

function layout(title: string, active: string, body: string) {
  const nav = [
    { href: "/", label: "Overview" },
    { href: "/readiness-lane", label: "Readiness Lane" },
    { href: "/red-flag-map", label: "Red Flag Map" },
    { href: "/board-story", label: "Board Story" },
    { href: "/deal-room", label: "Deal Room" },
    { href: "/verification", label: "Verification" },
    { href: "/docs", label: "Docs" }
  ];
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${title}</title><style>
  :root{--bg:#070a0f;--panel:#0b1220;--line:rgba(120,255,170,.18);--line2:rgba(120,255,170,.10);--text:#e9f3ff;--muted:rgba(233,243,255,.72);--muted2:rgba(233,243,255,.55);--good:#37ff8b;--cyan:#19c7ff;--warn:#ffcc66;--bad:#ff5c7a;--shadow:0 18px 60px rgba(0,0,0,.55);--mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;--sans:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial}
  *{box-sizing:border-box}body{margin:0;font-family:var(--sans);color:var(--text);background:radial-gradient(1200px 600px at 20% -10%, rgba(55,255,139,.18), transparent 60%),radial-gradient(900px 520px at 90% 0%, rgba(25,199,255,.16), transparent 55%),linear-gradient(180deg,#05070c 0%,#070a0f 35%,#05070c 100%)} .wrap{max-width:1280px;margin:0 auto;padding:24px 22px 80px}
  .topbar{display:flex;justify-content:space-between;gap:14px;border-bottom:1px solid var(--line2);padding-bottom:14px;margin-bottom:22px;font-family:var(--mono);font-size:11px;letter-spacing:.16em;color:var(--muted);text-transform:uppercase}.topbar .left{color:var(--good)}.topbar .right{text-align:right}
  .hero{border-radius:22px;padding:28px;border:1px solid var(--line);border-top:2px solid var(--cyan);background:linear-gradient(180deg, rgba(11,18,32,.95), rgba(8,14,26,.92));box-shadow:var(--shadow)} .hero h1{font-size:54px;line-height:.98;margin:0 0 14px;font-weight:800} .hero p{color:var(--muted);font-size:15px;line-height:1.55;max-width:760px}
  .chiprow,.navrow,.footer-links{display:flex;flex-wrap:wrap;gap:8px}.meta-chip,.navchip{font-family:var(--mono);font-size:11px;color:var(--muted);padding:8px 12px;border-radius:999px;border:1px solid var(--line);background:rgba(6,10,18,.4);text-decoration:none}.navchip.active{color:#071017;background:linear-gradient(135deg,var(--good),var(--cyan));font-weight:700}
  .section{margin-top:34px}.sh{display:flex;justify-content:space-between;gap:14px;padding-bottom:10px;border-bottom:1px solid var(--line2);margin-bottom:14px}.sh h2{margin:0;font-size:24px}.note{font-family:var(--mono);font-size:11px;color:var(--muted2);letter-spacing:.16em;text-transform:uppercase}
  .kpis,.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}@media (max-width:1000px){.kpis,.grid{grid-template-columns:repeat(2,1fr)}}@media (max-width:640px){.kpis,.grid{grid-template-columns:1fr}} .kpi,.card{border:1px solid var(--line);border-radius:14px;padding:16px;background:linear-gradient(180deg, rgba(11,18,32,.85), rgba(8,14,26,.65))}
  .kpi .v{font-family:var(--mono);font-size:26px;color:var(--cyan)}.kpi .lbl{font-family:var(--mono);font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted)}.kpi .h,.card p{font-size:13px;color:var(--muted);line-height:1.55}
  .card .name{font-family:var(--mono);font-size:11px;color:var(--good);letter-spacing:.18em;text-transform:uppercase}.card h3{margin:8px 0;font-size:20px}.status{font-family:var(--mono);font-size:10px;padding:4px 9px;border-radius:6px;border:1px solid currentColor;display:inline-block}.red{color:var(--bad)}.yellow{color:var(--warn)}.green{color:var(--good)}
  table{width:100%;border-collapse:separate;border-spacing:0;border:1px solid var(--line);border-radius:14px;overflow:hidden} th,td{padding:13px 14px;text-align:left;font-size:13.5px;vertical-align:top;color:var(--muted)} thead th{font-family:var(--mono);font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--muted2);border-bottom:1px solid var(--line);background:rgba(11,18,32,.5)}
  .footer{margin-top:30px;padding-top:14px;border-top:1px dashed var(--line2);display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;font-family:var(--mono);font-size:11px;color:var(--muted2)}
  </style><meta name="description" content="Exit Room is the board-ready diligence surface for red flags, exit readiness, and investor-facing narrative strength across Kinetic Gain’s strongest lanes."><meta property="og:type" content="website"><meta property="og:title" content="Exit Room"><meta property="og:description" content="Executive intelligence for exit readiness, board narrative, diligence gaps, downside risk, and investor confidence."><meta property="og:url" content="https://exit.kineticgain.com/"><meta property="og:site_name" content="Kinetic Gain"></head><body><div class="wrap"><div class="topbar"><div class="left">Kinetic Gain · Exit Room</div><div class="right"><div>exit readiness · diligence posture · board story</div><div>synthetic sample data only</div></div></div><section class="hero"><div class="chiprow"><span class="meta-chip">Exit-readiness intelligence layer</span><span class="meta-chip">Board and investor posture</span><span class="meta-chip">Synthetic sample data only</span></div><h1>One exit-readiness surface that shows which claims survive diligence, which red flags still threaten the narrative, what downside needs attention, and what leadership can defend in a board or investor room now.</h1><p>Exit Room sits after the scorecards, briefs, diligence packs, registry, radar, timing index, relationship graph, claims-vs-reality engine, and revenue scorecard. It turns that estate into one explicit readiness and deal-posture view.</p><div class="navrow">${nav.map((link) => `<a class="navchip${active === link.href ? " active" : ""}" href="${link.href}">${link.label}</a>`).join("")}</div></section>${body}<div class="footer"><div>exit-room · synthetic sample data only</div><div class="footer-links"><a class="meta-chip" href="https://github.com/mizcausevic-dev/">GitHub</a><a class="meta-chip" href="https://www.linkedin.com/in/mirzacausevic/">LinkedIn</a><a class="meta-chip" href="https://kineticgain.com/">Kinetic Gain</a></div></div></div></body></html>`;
}

const sev = (band: string) => band === "MUST_FIX" ? "red" : band === "SHORE_UP" ? "yellow" : "green";

export function renderOverview() {
  const s = summary();
  return layout("Exit Room", "/", `<section class="section"><div class="sh"><h2>Exit Snapshot</h2><div class="note">readiness · downside · board defense</div></div><div class="kpis"><div class="kpi"><div class="v">${s.items}</div><div class="lbl">themes</div><div class="h">Modeled themes tracked in the exit-readiness review set.</div></div><div class="kpi"><div class="v">${s.averageReadiness}</div><div class="lbl">average readiness</div><div class="h">How defensible the underlying systems and evidence are today.</div></div><div class="kpi"><div class="v">${s.averageInvestorConfidence}</div><div class="lbl">investor confidence</div><div class="h">How safely the current narrative can survive diligence pressure.</div></div><div class="kpi"><div class="v">${s.boardDefensibleItems}</div><div class="lbl">board-defensible</div><div class="h">Themes strong enough to defend in a board or investor room now.</div></div><div class="kpi"><div class="v">${s.missingEvidenceItems}</div><div class="lbl">missing evidence</div><div class="h">Themes that still rely on stale or missing proof.</div></div><div class="kpi"><div class="v">$${Math.round(s.downsideRiskUsd / 1000)}k</div><div class="lbl">modeled downside</div><div class="h">Modeled downside still attached to the current deal narrative.</div></div></div></section><section class="section"><div class="sh"><h2>What the room resolves</h2><div class="note">what defends · what breaks · what fixes next</div></div><div class="grid"><div class="card"><div class="name">priority</div><h3>What leadership can defend now</h3><p>${s.recommendation}</p></div><div class="card"><div class="name">red flags</div><h3>Which claims still attract diligence pain</h3><p>The room keeps missing evidence, narrative fragility, and modeled downside visible before they become surprise board questions.</p></div><div class="card"><div class="name">board story</div><h3>Which narrative is investable today</h3><p>AI governance, platform margin, FinTech, and the executive-intelligence meta story stay at the front when they are truly defendable.</p></div><div class="card"><div class="name">sequence</div><h3>What to fix before a process</h3><p>Every theme lands in must-fix, shore-up, or defend so leadership can act before the room gets harder.</p></div></div></section>`);
}

export function renderReadinessLane() {
  return layout("Exit Room — Readiness Lane", "/readiness-lane", `<section class="section"><div class="sh"><h2>Readiness Lane</h2><div class="note">buyer · diligence area · next move</div></div><table><thead><tr><th>Theme</th><th>Buyer</th><th>Diligence area</th><th>Band</th><th>Readiness</th><th>Red flag</th><th>Next move</th></tr></thead><tbody>${readinessLane().map((item) => `<tr><td><b>${item.theme}</b></td><td>${item.executiveBuyer}</td><td>${item.diligenceArea}</td><td><span class="status ${sev(item.priorityBand)}">${item.priorityBand}</span></td><td>${item.readinessScore}</td><td>${item.redFlagSummary}</td><td>${item.nextMove}</td></tr>`).join("")}</tbody></table></section>`);
}

export function renderRedFlagMap() {
  return layout("Exit Room — Red Flag Map", "/red-flag-map", `<section class="section"><div class="sh"><h2>Red Flag Map</h2><div class="note">evidence · downside · company tags</div></div><table><thead><tr><th>Theme</th><th>Evidence</th><th>Investor confidence</th><th>Downside risk</th><th>Company tags</th><th>Related surfaces</th></tr></thead><tbody>${redFlagMap().map((item) => `<tr><td><b>${item.theme}</b></td><td>${item.evidenceState}</td><td>${item.investorConfidenceScore}</td><td>$${item.downsideRiskUsd.toLocaleString()}</td><td>${item.companyTags.join(" · ")}</td><td>${item.relatedSurfaces.join("<br />")}</td></tr>`).join("")}</tbody></table></section>`);
}

export function renderBoardStory() {
  return layout("Exit Room — Board Story", "/board-story", `<section class="section"><div class="sh"><h2>Board Story</h2><div class="note">narrative · readiness · confidence</div></div><div class="grid">${boardStory().map((item) => `<div class="card"><div class="name">${item.executiveBuyer}</div><h3>${item.theme}</h3><p>${item.boardStory}</p><p>Readiness ${item.readinessScore} · Investor confidence ${item.investorConfidenceScore}</p></div>`).join("")}</div></section>`);
}

export function renderDealRoom() {
  return layout("Exit Room — Deal Room", "/deal-room", `<section class="section"><div class="sh"><h2>Deal Room</h2><div class="note">priority band · downside · next move</div></div><div class="grid">${dealRoom().map((item) => `<div class="card"><div class="name">${item.priorityBand} · $${Math.round(item.downsideRiskUsd / 1000)}k downside</div><h3>${item.theme}</h3><p>${item.nextMove}</p></div>`).join("")}</div></section>`);
}

export function renderVerification() {
  return layout("Exit Room — Verification", "/verification", `<section class="section"><div class="sh"><h2>Verification</h2><div class="note">diligence-safe claims only</div></div><div class="grid">${verification().map((item) => `<div class="card"><div class="name">verification</div><h3>${item}</h3><p>The room stays bounded to synthetic exit-readiness and diligence posture signals.</p></div>`).join("")}</div></section>`);
}

export function renderDocs() {
  return layout("Exit Room — Docs", "/docs", `<section class="section"><div class="sh"><h2>Docs</h2><div class="note">cli · apis · exit-readiness layer</div></div><div class="grid"><div class="card"><div class="name">cli</div><h3>Offline exit-room generation</h3><p><code>npx exit-room fixtures/exit-room.json --format summary</code> renders the same posture the dashboard exposes.</p></div><div class="card"><div class="name">apis</div><h3>Machine-readable payloads</h3><p>Use <code>/api/dashboard/summary</code>, <code>/api/readiness-lane</code>, <code>/api/red-flag-map</code>, and <code>/api/board-story</code> as the canonical JSON layers.</p></div><div class="card"><div class="name">product role</div><h3>Diligence layer after reality checks</h3><p>This room turns claims, signals, and relationship maps into one explicit exit-readiness and board-defense surface.</p></div></div></section>`);
}

export function renderSample() {
  return JSON.stringify(payload().sample, null, 2);
}
